### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'encode'

### ISSUE THREAD

**Issue by D-B-Miller** [skjerns/mat7.3#31]
Hi,
     I am attempting to load in a large MAT file (>3GB) which is >=v7.3. When I try and load in the file I get the following error

```python
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    data_dict = mat73.loadmat("UB_daq.mat")
  File "C:\Users\david\AppData\Local\Programs\Python\Python37\lib\site-packages\mat73\__init__.py", line 294, in loadmat
    dictionary = decoder.mat2dict(hdf5)
  File "C:\Users\david\AppData\Local\Programs\Python\Python37\lib\site-packages\mat73\__init__.py", line 90, in mat2dict
    d[var] = self.unpack_mat(hdf5[var])
  File "C:\Users\david\AppData\Local\Programs\Python\Python37\lib\site-packages\mat73\__init__.py", line 155, in unpack_mat
    return self.convert_mat(hdf5, depth, MATLAB_class=MATLAB_class)
  File "C:\Users\david\AppData\Local\Programs\Python\Python37\lib\site-packages\mat73\__init__.py", line 209, in convert_mat
    entry = self.unpack_mat(self.refs.get(r), depth+1)
  File "C:\Users\david\AppData\Local\Programs\Python\Python37\lib\site-packages\h5py\_hl\group.py", line 304, in get
    return self[name]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\david\AppData\Local\Programs\Python\Python37\lib\site-packages\h5py\_hl\group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "C:\Users\david\AppData\Local\Programs\Python\Python37\lib\site-packages\h5py\_hl\base.py", line 137, in _e
    name = name.encode('ascii')
AttributeError: 'numpy.ndarray' object has no attribute 'encode'
```

I suspect it might be related to the MATLAB_fields entry which stores the field names (attribute MATLAB_fields) as numpy arrays of bytes, but that's just a guess.

I can't send you the datafiles due to confidentiality restrictions.

**Comment by skjerns** [comment]
That is quite unfortunate :-/

I don't think there is a lot I can do without a test case.

What you can try:
1. remove all data/variables that are not affected
2. replace values within the given array with dummy/random values
3. send to me privately at cgkkibhj0rj@temp.mailbox.org

Also I suspect the error seems to be within the `h5py` library, so try your luck there!

**Comment by skjerns** [comment]
I did not recieve any data, so cannot replicate it.
